name: Yijia Xiong, PhD, Western University of Health Sciences, COMP-NW
markdown: kramdown

theme: jekyll-theme-slate
title: Dr. Yijia Xiong's Portfolios
description: Interdiscipline of Physical Chemistry, Biophysics, Biochemistry and Computer Programming!
